### ISSUE TITLE
Question about integration.

### ISSUE THREAD

**Issue by gedw99** [xlab/android-go#1]
Sorry to ask general questions but I have been using gomobile and noticed the android and iOS projects your working on.
It looks like a great approach and I want to ask a few questions in relation to my needs.

My GUI is web based using gopherjs with golang backend. The backend also goes on the mobiles with a websockets RPC between the GUI and backend all fully strongly typed due to gopherjs. 

So here is what I would need.
1. Need webview. To boot the GUI. 

2. Need RPC over web sockets.

When I use gomobile, i have to write all the RPC code in java and objective C, and then the golang code & web code uses them as a conduit.

But perhaps with the xlab approach I can write more in golang ?

**Comment by xlab** [comment]
@gedw99 Hi! I will outline the options that we have for cross-platform development of applications (not games).

The first and the best option is https://github.com/therecipe/qt.
Qt itself is a powerful framework that allows to do many things avoiding writing native platform code, but still keep the ability to use platform-native stuff like sensors, payment and advertising APIs and so on. The guy did amazing job creating the bindings and it runs seamlessly across many platforms in a single build. The Go code is the only code you'll need to write. Since you have a web app, you can boot into Qt's WebView to display the UI.

As for [gomobile](https://github.com/golang/mobile), they are good option to use when you already have lots of Javascript/Obj-C code and want to integrate some of Go libs into the project. The tool is mostly for experienced mobile developers who just want to try Go sometimes. They provide a framework that hides platform details, but sometimes may be to restrictive and limited due to this unification.

Now, about my projects. They are not achieving the same goal as gomobile, but rather fill the niche that gomobile doesn't suit well. First of all, [android-go](https://github.com/xlab/android-go) provides stateless and absolutely explicit 1:1 bindings to Android NDK. It's a low-level approach, but it's more flexible as you are free to do crazy stuff, for example initialize your own EGL context or don't initialize it at all. It is not good for SDK and Java interaction because I have no such plans and it's the topic of gomobile. It's good when you want to add some Go code and know what it does, with no extra dependencies and under-the-hood magic. The same goes for [ios-go](https://github.com/xlab/ios-go), I did two projects to run Vulkan / GLES surfaces with minimum mental overhead, they are not conventional apps.

I hope this answers your questions :)
It seems that my packages are not an option for your case.

**Comment by gedw99** [comment]
@xlab 
thanks for taking the time to look at this.

I played around with https://github.com/therecipe/qt.
I agree that the developer behind it is awesome, and really helpful.
I must admit i did not know that it supports a webview.
That would mean i have killed many problems in one hit:
- On mobile, no need for JAVA, Objective C code to write the RPC plumbing code.
- On Desktop, no need for Electron / Gallium.

I really though have to check how the QT WebView connects to my golang code.
At the moment i use GRPC and GRPC-gateway to expose all the code, which is probably really different to how QT WebView wants to work.

**Comment by gedw99** [comment]
will close..
